spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tealan
    password: postgres
    username: postgres
  jpa:
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        globally_quoted_identifiers: true
#        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
server:
  port: 8080

#logging:
#  file:
#    path: /logs
#    name: log
#  logback:
#    rollingpolicy:
#      max-file-size: 10MB
#      max-history: 10
#  level:
#    root: warn
#    com:
#      sandro: info
